language: php

php:
  - "5.3"
  - "5.4"

before_install:
  - sudo apt-get install db2exc
  - echo -e "db2inst1\ndb2inst1" | sudo passwd db2inst1
  - echo "/opt/ibm/db2/V9.7" | sudo pecl install ibm_db2
  - echo "extension=ibm_db2.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

before_script:
  - sudo -u db2inst1 -s -- "`pwd`/prepare_db.sh"

script: phpunit -c app
